const userActionTypes = {
    LOG_IN_REQUESTED: 'LOG_IN_REQUESTED',
    LOG_IN_SUCCESS: 'LOG_IN_SUCCESS',
    LOG_IN_FAILURE: 'LOG_IN_FAILURE',
    STORE_USER_EMAIL: 'STORE_USER_EMAIL',
    LOG_IN_START: 'LOG_IN_START',
    REGISTER_REQUESTED: 'REGISTER_REQUESTED',
    REGISTER_START: 'REGISTER_START',
    REGISTER_FAILURE: 'REGISTER_FAILURE',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    LOG_OUT: 'LOG_OUT',
}

export default userActionTypes;